Rio-Song-kr/GwisinRun

- Assets/JGH.meta
- Assets/JGH/Scene.meta
- Assets/JGH/Scene/PlayerMove.unity
- Assets/JGH/Scene/PlayerMove.unity.meta
- Assets/JGH/Script.meta
- Assets/JGH/Script/PlayerMove.cs
- Assets/JGH/Script/PlayerMove.cs.meta
> [Feat] 플레이어 이동기능 추가

- Assets/JGH/Script/PlayerMove.cs
- ProjectSettings/TimelineSettings.asset
> [Refactor] 키 입력 시스템 변경

- Assets/JGH/Scene/PlayerMove.unity
- Assets/JGH/Script/PlayerItemController.cs
- Assets/JGH/Script/PlayerMove.cs
> [Feat] 아이템 장착 및 해제 버리기 기능 구현

- Assets/JGH/Scene/PlayerMove.unity
- Assets/JGH/Script/PlayerMove.cs
> [Feat] 스태미너 기능 추가

- Assets/JGH/Scene/PlayerMove.unity
- Assets/JGH/Script/PlayerHide.cs
- Assets/JGH/Script/PlayerItemController.cs
- Assets/JGH/Script/PlayerMove.cs
아이템 중복 착용 및 아이템 장착한 상태에서 아이템 드랍안됨
> [Fix] 아이템 중복 착용 및 아이템 장착한 상태에서 아이템 드랍안됨

- Assets/LHW/Image/MouseCursor_Test.png.meta
- Assets/LHW/Material/TestMat.Cage.mat
- Assets/LHW/Material/TestMat.Cage.mat.meta
- Assets/LHW/Prefabs/Map/CagePrefeb.prefab
- Assets/LHW/Prefabs/Map/CagePrefeb.prefab.meta
- Assets/LHW/Prefabs/Map/DoorPrefeb.prefab
- Assets/LHW/Prefabs/Map/Switch.prefab
- Assets/LHW/Prefabs/Map/Switch.prefab.meta
- Assets/LHW/Scripts/ETC_NotUse/CursorUI/CursorUIController.cs
- Assets/LHW/Scripts/Events/Door/LHWPlayerController.cs
- Assets/LHW/Scripts/Events/Switch/SwitchController.cs
- Assets/LHW/Scripts/UI/ItemInfoUIController/ItemInfoUIController.cs
- Assets/LHW/TestScene/[LHW]TestScene.unity
- ProjectSettings/EditorBuildSettings.asset
- ProjectSettings/TagManager.asset
* 아이템 UI 출력 오류 수정(이슈 참고)
* SwitchController 기능 개편 - list로 오브젝트 참조하여 스위치 작동하도록 변경
* ItemInfoUIController 기능 개편 - 플레이어와 가까운 거리에 아이템이 있을 때에만 UI 출력하도록 개편
* 마우스 커서 오류 수정
> LHW 4/29 작업목록

- Assets/Resources/GameManager.prefab
- Assets/SDW/Scenes/LevelScene.unity
- Assets/SDW/Scenes/LevelScene.unity.meta
- Assets/SDW/Scenes/TitleScene.unity
- Assets/SDW/Scripts/Controller/Controls.inputactions
- Assets/SDW/Scripts/Manager/GameManager.cs
- Assets/SDW/Scripts/Manager/InputManager.cs
- Assets/SDW/Scripts/Manager/UIManager.cs
- Assets/SDW/Scripts/Manager/UIManager.cs.meta
- Assets/SDW/Scripts/Settings/GraphicsSetting.cs
- Assets/SDW/Scripts/Settings/InputSetting.cs
- Assets/SDW/Scripts/Struct/GraphicsModel.cs
- Assets/SDW/Scripts/TestScript/TestPlayerContoller.cs
- Assets/SDW/Scripts/UI/ControllSettingUI.cs
- Assets/SDW/Scripts/UI/ControllSettingUI.cs.meta
- Assets/SDW/Scripts/UI/GraphicsSettingUI.cs
- Assets/SDW/Scripts/UI/MainMenuUI.cs
- Assets/SDW/Scripts/UI/PauseMenuUI.cs
- Assets/SDW/Scripts/UI/PauseMenuUI.cs.meta
- Assets/SDW/Scripts/UI/ScrollUI.cs
- Assets/SDW/Scripts/UI/ScrollUI.cs.meta
- Assets/SDW/Scripts/UI/SettingsUI.cs
- Assets/SDW/Scripts/UI/SettingsUI.cs.meta
- Assets/Samples/Input System/1.14.0/Rebinding UI/RebindActionUI.cs
- ProjectSettings/EditorBuildSettings.asset
* 입력키 추가 - 버리기, Item 사용키, ESC(Pause) 추가
* UI 분리 작업
* LevelScene 추가
* PauseMenuUI 설정
* Graphics Setting 관련 버그 수정
* Scene 별 Controls 적용 문제 해결
> [Feat, Fix] 입력 키 추가, UI 분리 작업 외 버그 수정

- Assets/LHW/Animation/LHWCageAnimation/RoundcageAnimation.controller
- Assets/LHW/Animation/LHWCageAnimation/RoundcageAnimation.controller.meta
- Assets/LHW/Animation/LHWCageAnimation/anim_roundcage_idle.anim
- Assets/LHW/Animation/LHWCageAnimation/anim_roundcage_idle.anim.meta
- Assets/LHW/Animation/LHWCageAnimation/anim_roundcage_open.anim
- Assets/LHW/Animation/LHWCageAnimation/anim_roundcage_open.anim.meta
- Assets/LHW/TestScene/[LHW]TestScene.unity
애니메이션 수치 조정으로 충돌 발생하여, 기존 애니메이션 삭제 후 다시 제작하였습니다.
branch test, test2는 merge 후 삭제 부탁드립니다
> [Fix]cage 애니메이션 충돌로 새로 제작

- Assets/LHW/Scripts/UI/ItemInfoUIController/ItemInfoUIController.cs
- Assets/LHW/TestScene/[LHW]TestScene.unity
> [Fix]ItemUI 출력시 떨림 오류 수정

- Assets/Hyo/Script/Inventory.cs
- Assets/Hyo/Script/Item/UsableItem.cs
- Assets/JGH/Script/Player/PlayerHealth.cs
- Assets/JGH/Script/Player/PlayerMove.cs
- Assets/LHW/Scripts/UI/ItemInfoUIController/ItemInfoUIController.cs
- Assets/SDW/Scenes/[Merge] LevelOneScene(GetItem, ItemUI, InteractableObject).unity
* Pause UI 연결 관련 초안 작업 진행
* Bug가 있는 상태이며, 수정 예정
> [Feat] Pause UI 연결 관련 초안 작업 진행

- Assets/LHW/Prefabs/Map/CagePrefeb.prefab
- Assets/LHW/Prefabs/Map/Switch.prefab
- Assets/LHW/Scripts/Events/Switch/SwitchController.cs
SwitchController 내용 수정 및 프리팹 수정
> [Chores]SwitchController를 플레이어와 상호작용 가능하게 기능 수정

- Assets/JGH/Script/Player/PlayerHealth.cs
> [Chore] 확인용으로 빼둔 체력관련 제거

- Assets/JGH/Script/Player/PlayerController.cs
- Assets/JGH/Script/Player/PlayerHealth.cs
- Assets/JGH/Script/Player/PlayerIneration.cs
- Assets/JGH/Script/Player/PlayerMove.cs
- Assets/JGH/Script/Player/PlayerMoveCamera.cs
- Assets/JGH/Script/Player/PlayerUseItem.cs
- Assets/SDW/Scenes/TitleScene.unity
- Assets/SDW/Scenes/[Merge] LevelOneScene(Monster).unity
- Assets/SDW/Scenes/[Merge] LevelOneScene(Monster).unity.meta
- Assets/SDW/Scripts/Manager/GameManager.cs
- Assets/SDW/Scripts/UI/GameClearUI.cs
- Assets/SDW/Scripts/UI/GameOverUI.cs
- ProjectSettings/EditorBuildSettings.asset
> [Chore] UI 창 열렸을 시 플레이어 이동, 회전 방지

- Assets/JGH/Script/Player/PlayerController.cs
- Assets/JGH/Script/Player/PlayerIneration.cs
- Assets/JGH/Script/Player/PlayerMove.cs
- Assets/JGH/Script/Player/PlayerMoveCamera.cs
- Assets/JGH/Script/Player/PlayerUseItem.cs
- Assets/SDW/Scenes/[Merge] LevelOneScene(GetItem, ItemUI, InteractableObject).unity
- Assets/SDW/Scenes/[Merge] LevelOneScene(Monster).unity
* UI 창 열렸을 시 플레이어 이동, 회전 방지 추가 후 Start/Pasue UI에서 플레이어가 위로 올라가는 버그 수정
> [Fix] UI 창 열렸을 시 플레이어 이동, 회전 방지 추가 후 버그 수정

- Assets/JGH/Script/Player/PlayerMoveCamera.cs
- Assets/Prefabs/Character/Player_V2_Edit.prefab
> [Fix] 충돌체 접촉 문제 수정, 앉은 시야 수정

- Assets/Hyo/Script/Inventory.cs
- Assets/JGH/Script/Player/PlayerUseItem.cs
- Assets/SDW/Scripts/Controller/Controls.inputactions
- Assets/SDW/Scripts/Manager/InputManager.cs
- Assets/SDW/Scripts/TestScript/TestPlayerContoller.cs
* 기존 아이템 선택 시 바로 사용되는 방식에서 아이템 선택 시 단순히 선택으로 변경
* 아이템 사용키 별도 추가
> [Feat] 아이템 사용키 추가 및 아이템 선택과 사용 로직 변경

- Assets/JGH/Script/Player/PlayerHide.cs
- Assets/Prefabs/Character/Player_V2_Edit.prefab
- Assets/SDW/Scenes/[Merge] LevelOneScene(UITest).unity
* Trigger 방식에서 물리 기반 검사(CheckSphere)로 변경
> [Fix] 플레이어가 책상을 뚫고 튀어나오는 버그

- Assets/Hyo/Script/Inventory.cs
- Assets/LHW/Scripts/Events/Door/DoorController.cs
- Assets/LHW/Scripts/Events/Door/IsLockedDoor.cs
- Assets/SDW/Scenes/[Merge] LevelOneScene(UITest).unity
- Assets/Scenes/[Template] LevelDesign.unity
* Locked Door와 인벤토리에 Key 여부 확인 후 제거 관련 스크립트 수정
> [Chore] Locekd Door 관련 스크립트 수정

- Assets/Hyo/Script/Inventory.cs
- Assets/Hyo/Script/Item/Item.cs
- Assets/JGH/Script/Player/PlayerIneration.cs
- Assets/Prefabs/LevelDesign/Room(Medium) Type2.prefab
- Assets/Prefabs/LevelDesign/Room(Small) Type1.prefab
- Assets/Prefabs/LevelDesign/Template/RoomTemplate(Medium2).prefab
- Assets/Prefabs/LevelDesign/Template/RoomTemplate(Small).prefab
- Assets/SDW/Prefabs/UI/Game/Game Level Ratio.prefab
- Assets/SDW/Scenes/[Merge] LevelOneScene(UITest).unity
- Assets/SDW/Scripts/UI/PauseMenuUI.cs
- Assets/Scenes/[Template] LevelAssets.unity
- Assets/Scenes/[Template] LevelDesignTest.unity
- Assets/Scenes/[Template] LevelDesignTest.unity.meta
* Drop Item과 Throw Item 구현
* Template 프리팹 수정
> [Feat] Drop Item 구현 및 Template 프리팹 수정

- Assets/LHW/Animation/LHWDeskDrawerAnimation/desk_drawer_01.controller
- Assets/LHW/Material/haunted_mansion.mat
- Assets/LHW/Material/haunted_mansion.mat.meta
- Assets/LHW/Prefabs/Map/CabinetPrefeb.prefab
- Assets/LHW/Prefabs/Map/ShelfPrefab_1x1.prefab
- Assets/LHW/Prefabs/Map/ShelfPrefeb_2x1-1.prefab
- Assets/LHW/Prefabs/Map/ShelfPrefeb_2x2.prefab
- Assets/LHW/Scripts/Events/Desk/DeskDrawerController.cs
- Assets/LHW/TestScene/[LHW]TestScene.unity
- Assets/Prefabs/Interactable/DeskPrefeb.prefab
* 아웃라인이 정상적으로 출력되지 않는 오류 수정
* 다만 플레이어와 상호작용을 연결하는 과정에서 문제가 있어 아직 직접적인 연결을 하진 못함
문제상황
온오프를 하는 과정에서 상호작용한 물체가 어떤 것인지 판별하는 절차가 필요하며 상호작용 가능한 물체를 벗어났을 때 오프할 수 있는 방법이 없음
해결 방법은 많이 복잡해질 것으로 예상됨... 고민해보겠습니다
현재 생각할 수 있는 방법은 상호작용 가능한 물체 전체에 인터페이스를 걸어야 할 것 같은데 제가 멋대로 수정할 스케일이 아니라서 회의를 해봐야 할 것 같습니다
해당 브렌치는 계속 사용 예정입니다 삭제하지 말아주세요
> [Fix]아웃라인 출력 관련 오류 수정

- Assets/Prefabs/LevelDesign/Room(Medium) Type1.prefab
- Assets/Prefabs/LevelDesign/Room(Medium) Type2.prefab
- Assets/Prefabs/LevelDesign/Room(Small) Type1.prefab
- Assets/Prefabs/LevelDesign/Template/RoomTemplate(Big).prefab
- Assets/Prefabs/LevelDesign/Template/RoomTemplate(Medium1).prefab
- Assets/Prefabs/LevelDesign/Template/RoomTemplate(Medium2).prefab
- Assets/Prefabs/LevelDesign/Template/RoomTemplate(Small).prefab
- Assets/Render/MainCamera Profile.asset
- Assets/Resources/GameManager.prefab
- Assets/SDW/Materials/Mat_Test.mat
- Assets/SDW/Prefabs/UI/Game Level Canvas.prefab
- Assets/SDW/Prefabs/UI/Game/Popup Dialog Container.prefab
- Assets/SDW/Prefabs/UI/Settings/Graphics Setting Dialog Menu.prefab
- Assets/SDW/Scenes/TitleScene.unity
- Assets/SDW/Scenes/[Merge] LevelOneScene(UITest) 2.unity
- Assets/SDW/Scenes/[Merge] LevelOneScene(UITest) 2.unity.meta
- Assets/SDW/Scripts/Manager/GameManager.cs
- Assets/SDW/Scripts/Manager/SceneChangeManager.cs
- Assets/SDW/Scripts/Manager/SceneChangeManager.cs.meta
- Assets/SDW/Scripts/UI/GameClearUI.cs
- Assets/SDW/Scripts/UI/GameOverUI.cs
- Assets/SDW/Scripts/UI/GraphicsSettingUI.cs
- Assets/SDW/Scripts/UI/NewGamePanelUI.cs
- Assets/SDW/Scripts/UI/PauseMenuUI.cs
* Template의 door를 interactable door로 교체
* Graphics Setting 최댓값 변경
* SceneChangeManager 추가(초기 셋팅)
* UICamera의 Post-process를 UIPostprocessing으로 변경
> [Chore, Fix] Template door 교체 및 Graphics Setting 변경, SceneChangeManager 추가, TitleScene의 UICamera 레이어 변경

- Assets/LHW/Material/ShaderTest.mat
- Assets/LHW/Prefabs/UI/PlayerStatusUI.prefab
- Assets/LHW/Prefabs/UI/PlayerStatusUI.prefab.meta
- Assets/LHW/Scripts/Events/Desk/DeskDrawerController.cs
- Assets/LHW/Scripts/UI/PlayerUI.meta
- Assets/LHW/Scripts/UI/PlayerUI/HealthUI.cs
- Assets/LHW/Scripts/UI/PlayerUI/HealthUI.cs.meta
- Assets/LHW/Scripts/UI/PlayerUI/StaminaUI.cs
- Assets/LHW/Scripts/UI/PlayerUI/StaminaUI.cs.meta
- Assets/LHW/TestScene/[LHW]TestScene.unity
* 현재 아웃라인 관련 오류로 해당 스크립트 부분 주석 처리
* 플레이어의 체력과 스태미나를 표시하는 UI 기능 구현
에셋 다운 부틱드립니다 - Action RPG GUI
해당 브렌치 merge후 삭제 부탁드립니다
> LHW 플레이어 상태 UI 기능 구현

- Assets/Hyo/Script/Enum/ItemType.cs
- Assets/JGH/Script/Player/PlayerHealth.cs
- Assets/JGH/Script/Player/PlayerMove.cs
- Assets/JGH/Script/Player/PlayerUseItem.cs
- Assets/Prefabs/Interactable/Items.meta
- Assets/Prefabs/Interactable/Items/HeartPotion_Negative.prefab
- Assets/Prefabs/Interactable/Items/HeartPotion_Negative.prefab.meta
- Assets/Prefabs/Interactable/Items/HeartPotion_Positive.prefab
- Assets/Prefabs/Interactable/Items/HeartPotion_Positive.prefab.meta
- Assets/Prefabs/Interactable/Items/Key.prefab
- Assets/Prefabs/Interactable/Items/Key.prefab.meta
- Assets/Prefabs/Interactable/Items/SpeedPotion_Negative.prefab
- Assets/Prefabs/Interactable/Items/SpeedPotion_Negative.prefab.meta
- Assets/Prefabs/Interactable/Items/SpeedPotion_Positive.prefab
- Assets/Prefabs/Interactable/Items/SpeedPotion_Positive.prefab.meta
- Assets/Prefabs/Interactable/Items/StaminaPotion_Nagative.prefab
- Assets/Prefabs/Interactable/Items/StaminaPotion_Nagative.prefab.meta
- Assets/Prefabs/Interactable/Items/StaminaPotion_Positive.prefab
- Assets/Prefabs/Interactable/Items/StaminaPotion_Positive.prefab.meta
- Assets/SDW/Scenes/[Merge] LevelOneScene(UITest).unity
* 포션, 열쇠 프리팹 제작
* Speed, Stamina 아이템 사용 관련 수정
> [Feat] 포션, 열쇠 프리팹 제작 및 Speed, Stamina 아이템 사용 관련 수정

- Assets/LHW/MapCreate/[Template] LevelDesign-Won.unity
프리팹 정리로 맵 내용 수정
*브렌치는 유지 부탁드립니다
> [Fix]Prefab 정리로 맵 프리팹 정리

- Assets/JGH/Script/Player/PlayerHealth.cs
- Assets/JGH/Script/Player/PlayerMove.cs
- Assets/JGH/Script/Player/PlayerMoveCamera.cs
- Assets/JGH/Script/Player/PlayerUseItem.cs
- Assets/LHW/Scripts/UI/PlayerUI/HealthUI.cs
- Assets/LHW/Scripts/UI/PlayerUI/StaminaUI.cs
> [Fix] 플레이어 체력 및 스태미너 관련 Null 오류

- Assets/LHW/Scripts/UI/PlayerUI/HealthUI.cs
- Assets/LHW/Scripts/UI/PlayerUI/StaminaUI.cs
UI 비정상 작동 오류를 수정하고, 정상 작동 테스트 완료함 - 온오프 기능 적용은 추후 진행 예정
> [Fix] UI 비정상작동 오류 수정 - 온오프 기능은 추후 적용

- Assets/SDW/Prefabs/UI/Game/Game Level Ratio.prefab
- Assets/SDW/Prefabs/UI/Game/Game Start Panel Dialog.prefab
- Assets/SDW/Scenes/[Merge] LevelOneScene(UITest).unity
- Assets/SDW/Scripts/UI/GameClearUI.cs
- Assets/SDW/Scripts/UI/GameOverUI.cs
- Assets/SDW/Scripts/UI/GameStartUI.cs
- Assets/SDW/Scripts/UI/PauseMenuUI.cs
> [Chore] Player Status UI와 연결

- Assets/JGH/Script/Player/PlayerController.cs
- Assets/JGH/Script/Player/PlayerMove.cs
- Assets/JGH/Script/Player/PlayerMoveCamera.cs
- Assets/JHS/Scripts/Monster/MonsterState.cs
> [Refactor] player static 모두 제거

- Assets/JGH/Script/Player/PlayerMove.cs
- Assets/JGH/Script/Player/PlayerMoveState.cs
- Assets/JGH/Script/Player/PlayerMoveState.cs.meta
- Assets/Resources/GameManager.prefab
- Assets/SDW/Scenes/[Merge] LevelOneScene(UITest).unity
- Assets/SDW/Scripts/Manager/GameManager.cs
- Assets/Scripts/Settings/AudioSetting.cs
* Title 씬 배경음악 변경
* Game 씬 배경음악 추가
* Player Idle, Walk, Runt 소리 추가
> [Feat] 배경음악 변경 및 Player Idle, Walk, Runt 소리 추가

- Assets/JHS/Scenes/[Merge] LevelOneScene(UITest).meta
- Assets/LHW/MapCreate/[Template] LevelDesign-Won.unity
- Assets/Prefabs/Interactable/DeskPrefeb _ver2.prefab
스테이지 맵 세부수정 및 책상 프리팹만 우선적으로 서랍 충돌체 수정
* 해당 브렌치는 삭제 부탁드립니다.
> 스테이지 맵 세부수정 및 책상 프리팹만 우선적으로 서랍 충돌체 수정

- Assets/Prefabs/LevelDesign/Template/Corridor(Windows).prefab
- Assets/Prefabs/LevelDesign/Template/Corridor(Windows, No Floor).prefab
- Assets/Prefabs/LevelDesign/Template/WallWindow.prefab
- Assets/Prefabs/LevelDesign/Template/WallWindow.prefab.meta
- Assets/SDW/Scenes/LevelOne.unity
- Assets/SDW/Scenes/[Merge] LevelOneScene(UITest).unity
- Assets/Scenes/[Template] LevelAssets.unity
> [Fix] Corridor Window Template 수정

- Assets/LHW/MapCreate/[Template] LevelDesign-Won.unity
- Assets/LHW/Scripts/Events/Desk/DeskDrawerController.cs
* Level Design - Won 은 테스트 이전까지는 수정 없을 예정
* 맵 하나 더 제작할 예정
> [Feat]스테이지 맵 세부 수정6 - 마무리

- Assets/Prefabs/Interactable/DeskPrefeb _ver2.prefab
책상 초기 좌표 이상으로 영점조절 및 서랍 내 바닥면 충돌체가 얇아 아이템이 서랍에 가리는 현상 수정
> [Fix]Desk_ver2 프리팹 초기좌표 수정 및 충돌체 수정

- Assets/LHW/MapCreate/[Template] LevelDesign-Won2.unity
- Assets/LHW/MapCreate/[Template] LevelDesign-Won2.unity.meta
> [Feat]Map 디자인 2 완성

- Assets/LHW/MapCreate/[Template] LevelDesign-Won.unity
- Assets/LHW/MapCreate/[Template] LevelDesign-Won2.unity
> [Fix]맵 오브젝트 Missing 수정 및 위치 수정

- Assets/Prefabs/Interactable/Items/Key.prefab
- Assets/Scenes/LevelOne.unity
- Assets/Scenes/LevelThree.unity
- Assets/Scenes/LevelTwo.unity
> [Fix] 레벨 프리팹 위치 조절 및 불필요한 프리팹 제거

- Assets/Prefabs/Interactable/Items/Key.prefab
- Assets/Prefabs/Interactable/Switch.prefab
> [Feat]열쇠 및 스위치 OutlineShader 적용

- Assets/Scenes/LevelTwo.unity
> [Fix] 게임 중 철창 하나의 스위치와의 연결 해제 문제 발견 및 수정

- Assets/Prefabs/UI/Game Level Canvas.prefab
- Assets/Prefabs/UI/Game/Game Level Ratio.prefab
- Assets/SDW/Scripts/UI/GameClearUI.cs
- Assets/SDW/Scripts/UI/GameOverUI.cs
- Assets/SDW/Scripts/UI/GameStartUI.cs
- Assets/SDW/Scripts/UI/PauseMenuUI.cs
- Assets/Scenes/LevelOne.unity
- Assets/Scenes/LevelThree.unity
- Assets/Scenes/LevelTwo.unity
* CenterPoint 관련 UI 처리 수정
* 몬스터 시야각 180도로 수정
> [Fix] CenterPoint 관련 UI 처리 수정, 몬스터 시야각 180도로 수정

- Assets/Prefabs/UI/Game/Main Menu Ratio.prefab
- Assets/Prefabs/UI/Title Canvas.prefab
- Assets/SDW/Scripts/UI/MainMenuUI.cs
- Assets/Scenes/LevelFour.unity
- Assets/Scripts/Settings/GraphicsSetting.cs
- ProjectSettings/ProjectSettings.asset
* 창 모드 버그
* LevelFour 서랍장 수정
* Exit 관련 버그 수정
* 빌드 시 게임 아이콘 추가
> [Fix] 창 모드 버그, LevelFour 서랍장 수정, Exit 관련 버그 수정

- Assets/Scripts/Settings/GraphicsSetting.cs
- ProjectSettings/ProjectSettings.asset
> [Fix] 해상도 문제 해결

- Assets/JGH/Scene/[Template] LevelDesignFinal.unity
> [Chore] 씬 추가

- Assets/Documents/Team_11.pptx.meta
- Assets/Documents/기획.md.meta
- Assets/Documents/팀원.md.meta
- Assets/SDW/Scripts/UI/InventoryUI.cs
> [Fix] Inventory 선택창 표시 버그 해결

- Assets/Documents/Team_11.pptx.meta
- Assets/JGH/Scene/[Template] LevelDesignFinal.unity
- Assets/Scenes/LevelFour.unity
> [Chore] 안개효과 추가

- Assets/JGH/Scene/[Template] LevelDesignFinal.unity
> [Fix] 몬스터 태그 추가
